Path_Plan:
  ros__parameters:
    left_speed: 110
    right_speed: 150
    straight_speed: 95
    pweight: 17.0  # base turning torque "speed" factor
    iweight: 1.8  # turning torque "acceleration" factor
    min_torque: 0
    max_torque: 25
    not_centered_width: 0.4
    centered_width: 0.2
    close_centered_width: 0.03
