Path_Plan:
  ros__parameters:
    left_speed: 110
    right_speed: 150
    straight_speed: 95
    pweight: 15
    iweight: 2
    min_error: 0
    max_error: 22
    not_centered_width: 0.25
    centered_width: 0.25

